/**:
  ros__parameters:
    camera_name: "rspr_r"
    camera_type: "chameleon"
    serial_number: "17496121"
    frame_id: "camera_rspr_r_optical"
    parameter_file: "/opt/ros_ws/install/av_camera_launch/share/av_camera_launch/config/chameleon.yaml"
    camerainfo_url: "file:///opt/ros_ws/install/av_camera_launch/share/av_camera_launch/config/rspr_r_calib.yaml"
    debug: False
    compute_brightness: False
    dump_node_map: False
    adjust_timestamp: True
    gain_auto: "Continuous"
    exposure_auto: "Off"
    exposure_time: 4000
    reverse_x: False
    reverse_y: False
    offset_x: 98
    offset_y: 544
    image_width: 2272
    image_height: 1056
    pixel_format: "BayerRG8"  # 'BayerRG8 'RGB8' or 'Mono8'
    trigger_selector: "FrameStart"
    trigger_mode: "On"
    trigger_source: "Line3"
    trigger_delay: 0
    trigger_overlap: "ReadOut"
    chunk_mode_active: True
    chunk_selector_frame_id: "FrameID"
    chunk_enable_frame_id: True
    chunk_selector_exposure_time: "ExposureTime"
    chunk_enable_exposure_time: True
    chunk_selector_gain: "Gain"
    chunk_enable_gain: True
    chunk_selector_timestamp: "Timestamp"
    chunk_enable_timestamp: True
